export const SuccessMessage = {
    SUCCESSFUL: "SUCCESSFUL"
}

export const ErrorMessage = {
    PHONE_ALREADY_EXIST: "PHONE_ALREADY_EXIST",
    REQUIRED_OR_INVALID: "REQUIRED_OR_INVALID: ",
    SERVER_ERROR: "SERVER_ERROR",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    BAD_REQUEST: "BAD_REQUEST",
    REQUIRED_DATA_ENCRYPTION: "REQUIRED_DATA_ENCRYPTION",
    REQUIRED_DATA_DECRYPTION: "REQUIRED_DATA_DECRYPTION",
    REQUIRED_PASSWORD_TO_HASH: "REQUIRED_PASSWORD_TO_HASH",
    REQUIRED_PASSWORD_TO_COMPARE: "REQUIRED_PASSWORD_TO_COMPARE",
    GENERATE_TOKEN_FAIL: "GENERATE_TOKEN_FAIL",
    SOMETHING_WENT_WRONG_IN_DB: "SOMETHING_WENT_WRONG_IN_DB",
}